module.exports = [
  {
    organizationName: 'Hope Welfare Centre',
    registrationNumber: 'NGO-DEL-2019-332',
    address: 'Karol Bagh, New Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    latitude: 28.651,
    longitude: 77.192,
    contactPerson: 'Priya Sharma',
    phone: '+91 98765 43210',
    beneficiaryCount: 180,
    dailyFoodRequirement: 150,
    storageCapacity: 200,
    foodPreferences: ['Vegetarian', 'Vegan'],
    verificationStatus: 'VERIFIED',
    email: 'ngo@akshayashelter.org',
    password: 'password123',
    name: 'Akshaya Shelter Foundation',
  },
  {
    organizationName: 'Annapurna Community Centre',
    registrationNumber: 'NGO-DEL-2020-441',
    address: 'Lajpat Nagar, New Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    latitude: 28.5677,
    longitude: 77.2433,
    contactPerson: 'Rajesh Kumar',
    phone: '+91 98112 34567',
    beneficiaryCount: 120,
    dailyFoodRequirement: 100,
    storageCapacity: 150,
    foodPreferences: ['Vegetarian', 'Non-Vegetarian'],
    verificationStatus: 'VERIFIED',
    email: 'info@hopekitchen.org',
    password: 'password123',
    name: 'Hope Community Kitchen',
  },
  {
    organizationName: 'Care & Share Foundation',
    registrationNumber: 'NGO-DEL-2018-109',
    address: 'Civil Lines, North Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    latitude: 28.6814,
    longitude: 77.2229,
    contactPerson: 'Dr. Ananya Roy',
    phone: '+91 97171 88990',
    beneficiaryCount: 250,
    dailyFoodRequirement: 200,
    storageCapacity: 250,
    foodPreferences: ['Vegetarian', 'Vegan', 'Egg'],
    verificationStatus: 'VERIFIED',
    email: 'ananya@rotarymeals.org',
    password: 'password123',
    name: 'Rotary Meals & Welfare Centre',
  },
  {
    organizationName: 'Jan Seva Community Shelter',
    registrationNumber: 'JANSEVA-REG-2026-DRAFT',
    address: 'Yamuna Pushta, East Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    latitude: 28.641,
    longitude: 77.258,
    contactPerson: 'Vikramjit Singh',
    phone: '+91 99990 12345',
    beneficiaryCount: 210,
    dailyFoodRequirement: 180,
    storageCapacity: 180,
    foodPreferences: ['Vegetarian'],
    verificationStatus: 'PENDING',
    email: 'janseva.delhi@gmail.com',
    password: 'password123',
    name: 'Jan Seva Community Shelter',
  },
];
